rails-mister-cocktail/config/routes.rb
Rails.application.routes.draw do


  # get    "cocktails",          to: "cocktails#index"

  # get    "cocktails/new",      to: "cocktails#new", as: :new_cocktail
  # post   "cocktails",          to: "cocktails#create"
  # # NB: The `show` route needs to be *after* `new` route.
  # get    "cocktails/:id",      to: "cocktails#show", as: :cocktail

  # # get    "cocktails/:id/edit", to: "cocktails#edit"
  # # patch  "cocktails/:id",      to: "cocktails#update"

  # delete "cocktails/:id",      to: "cocktails#destroy"

  #  # resources :cocktails

  # get    "doses",          to: "doses#index"

  # get    "doses/new",      to: "doses#new", as: :new_dose
  # post   "doses",          to: "doses#create"

  # # NB: The `show` route needs to be *after* `new` route.
  # get    "doses/:id",      to: "doses#show", as: :dose

  # # get    "doses/:id/edit", to: "doses#edit"
  # # patch  "doses/:id",      to: "doses#update"

  # delete "doses/:id",      to: "doses#destroy"

  root to: 'pages#home'
  resources :doses, only: [:destroy]
  resources :cocktails do
    resources :reviews, only: [:new, :create]
    resources :doses, only: [:index,:new, :create] do
      resources :ingredients, only: [:index, :new, :create, :destroy]
      end
    end
  end

rails-mister-cocktail/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-mister-cocktail/app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, uniqueness: true, presence: true
end

rails-mister-cocktail/app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :cocktail, uniqueness: { scope: :ingredient }
  validates :description, presence: true
end

rails-mister-cocktail/app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, uniqueness: true, presence: true

end

rails-mister-cocktail/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :content, presence: true
  validates :rating, presence: true, length: { in: 1..5 }
end

rails-mister-cocktail/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails-mister-cocktail/app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.page(params[:page]).per(6)
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to new_cocktail_dose_path(@cocktail)
    else
      render :new
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@dose.cocktail)
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

   private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

rails-mister-cocktail/app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def index
    @doses = Dose.all
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredient = Ingredient.all
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    if @dose.save
      redirect_to new_cocktail_dose_path(@dose.cocktail)
    else
      render :new
    end
  end

  # def edit
  #   @cocktail = Cocktail.find(params[:cocktail_id])
  #   @dose = Dose.find(params[:id])
  # end

  # def update
  #   @dose = Dose.find(params[:id])
  #   @dose.cocktail.update(dose_params)
  #   redirect_to cocktail_path(@dose.cocktail)
  # end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to new_cocktail_dose_path(@dose.cocktail)
  end

   private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

rails-mister-cocktail/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.find(params[:dose_id])

    @ingredient = Ingredient.new
  end

  def create
    @ingredient = ingredient.new(ingredient_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    # we need `restaurant_id` to asssociate review with corresponding restaurant
    @dose.cocktail = Dose.find(params[:dose_id])
    @ingredient = Ingredient.find(params[:ingredient_id])


    if @ingredient.save
      redirect_to new_cocktail_dose_path(@cocktail)
    else
      render :new
    end
  end


  def destroy

    @ingredient = ingredient.find(params[:id])
    @ingredient.destroy
  end

   private

  def ingredient_params
    params.require(:ingredient).permit(:name, :cocktail_id, :dose_id)
  end
end

rails-mister-cocktail/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

rails-mister-cocktail/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.cocktail = Cocktail.find(params[:cocktail_id])
    if @review.save
      redirect_to cocktail_path(@review.cocktail)
    else
      render :new
    end
  end


    private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

rails-mister-cocktail/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-mister-cocktail/app/helpers/cocktails_helper.rb
module CocktailsHelper
end

rails-mister-cocktail/app/helpers/doses_helper.rb
module DosesHelper
end

rails-mister-cocktail/app/helpers/reviews_helper.rb
module ReviewsHelper
end

rails-mister-cocktail/app/views/cocktails/edit.html.erb
edit.html.erb
<div class="banner">
  <div class="container d-flex justify-content-start">
    <div class="cocktail-show">
      <h1><%= @cocktail.name %></h1>
      <div class="cocktail-recipe">
        <% counter = 0 %>
        <% @cocktail.doses.each do |dose| %>
        <p class="mb-4"><span class="counter"><%= counter += 1 %></span><%= dose.description.capitalize %> of <%= dose.ingredient.name.capitalize %>
        </p>
        <% end %>
      </div>
      <%= simple_form_for([@cocktail, @dose]) do |f| %>
      <div class='form-input'>
        <%= f.input :description %>
        <%= f.association :ingredient %>
        <div class="btn mt-2 pl-0 mb-4">
          <%= f.button :submit, 'Update', class:'dose-btn', method: :patch, data: { confirm: "Are you sure?" } %>
        </div>
        <% end %>


      </div>
    </div>
  </div>
</div>

rails-mister-cocktail/app/views/cocktails/index.html.erb
<div class="banner">
  <div class="container d-flex align-items-center justify-content-start" style=" height: auto;">
    <div class="home mb-4 pt-4">
          <div class="d-flex align-items-center justify-content-between ">

      <h1 class="mb-4 mt-4 pt-2">Cocktails
<!--         <span> (scroll)</span>
 -->      </h1>
       <div class="btn mb-4 mt-4 pt-4">
        <%= link_to "New cocktail", new_cocktail_path %>
      </div>
    </div>
      <!-- <div class="cards">
       <% counter = 0  %>
        <% @cocktails.each do |cocktail| %>
          <div class="card-category cocktail-show" >
           <span class="counter"><%= counter += 1  %></span>
          <h2><%= link_to cocktail.name.capitalize, cocktail_path(cocktail) %></h2>
        </div>
        <% end %>

      </div> -->
</div>
  </div>
<div class="container cocktail-show card-bg d-flex justify-content-start flex-column">
  <div class="row pr-4 pl-4 pt-4 pb-0">
    <% @cocktails.each do |cocktail| %>
      <div class="col-12 col-md-12 col-lg-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://source.unsplash.com/500x400/?cocktail');">
          <div class="card-description">
            <h2 class="cocktail-name"><%= cocktail.name %></h2>
          </div>
          <%= link_to "", cocktail_path(cocktail), class: 'card-link' %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="pagination pl-4 pt-0 pb-4">
    <%= paginate @cocktails %>
  </div>
</div>

rails-mister-cocktail/app/views/cocktails/new.html.erb
<div class="banner d-flex align-items-center flex-direction-column" style=" height: auto;">

  <div class="container d-flex justify-content-start" >
    <div class="home">
      <h1>Cocktail's name</h1>
<%= simple_form_for [@cocktail] do |f| %>
  <%= f.input :name, placeholder: "Write the name here..."%>

      <div class="btn mt-2 pl-0 mb-4">
        <%= f.button :submit, 'Add your cocktail', class:'dose-btn' %>
      </div>
      <% end %>

    </div>
  </div>
</div>

rails-mister-cocktail/app/views/cocktails/show.html.erb
<div class="banner">

  <div class="container d-flex justify-content-start align-items-center" style=" height: auto;">
    <div class="cocktail-show ">
      <div class="d-flex align-items-center justify-content-start">
        <h1 class="mt-4 mb-4 mr-4"><%= @cocktail.name.capitalize %></h1>
        <div class="btn mt-2 pl-0 mb-2">
          <%= link_to new_cocktail_dose_path(@cocktail) do %>
          <i class="fas fa-pencil-alt"></i>
          <% end %>
          <%= link_to "Delete", cocktail_path(@cocktail),
          method: :delete,
          data: { confirm: "Are you sure?" }  %>
        </div>
      </div>
      <h2 class="mt-4"><%= "To make some wicked #{@cocktail.name.capitalize}s,"%></h2>
      <h2 class="mb-4"><%= "all you need is ->" %></h2>
      <div class="cocktail-recipe">
        <% counter = 0 %>
        <% @cocktail.doses.each do |dose| %>
        <div class="d-flex align-items-center justify-content-between">
          <p class="mb-4" style="font-size: 1.3em"><span class="counter"><%= counter += 1 %></span><%= dose.description.capitalize %> of <%= dose.ingredient.name.capitalize %></p>
        </div>
        <% end %>
      </div>
      <!-- -------------------------- REVIEWS -----------------------------
      -->
      <div class="reviews cocktail-show mb-4">
        <div class="d-flex align-items-center justify-content-start mb-3 ">
          <h2>Reviews</h2>
          <div class="btn">
            <%= link_to new_cocktail_review_path(@cocktail) do %>
            <i class="fas fa-plus"></i>
            <% end %>
            <%= link_to "Back to Cocktails", cocktails_path %>
          </div>
        </div>
        <% if @cocktail.reviews.empty? %>
        <p>Be the first to let a review</p>
        <% else %>
        <ul class="list-group">
          <% @cocktail.reviews.each do |review| %>
          <li class="reviews-list d-flex justify-content-start align-items-center mb-2">
            <span class="rating badge badge-primary badge-pill d-flex justify-content-around">
              <% counter = 0 %>
              <% 5.times do %>
              <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %> stars"></i>
              <% counter += 1 %>
              <% end %>
            </span>
            <p class="reviews"><%= review.content.capitalize %></p>
          </li>
          <% end %>
        </ul>
        <% end %>
      </div>
    </div>
    <!-- ------------------------- END REVIEWS ----------------------------
    -->
  </div>
</div>
</div>

rails-mister-cocktail/app/views/doses/edit.html.erb
<div class="banner">
  <div class="container d-flex justify-content-start">
    <div class="cocktail-show">
      <h1><%= @cocktail.name %></h1>
      <div class="cocktail-recipe">
        <% counter = 0 %>
        <% @cocktail.doses.each do |dose| %>
        <p class="mb-4"><span class="counter"><%= counter += 1 %></span><%= dose.description.capitalize %> of <%= dose.ingredient.name.capitalize %>
        </p>
        <% end %>
      </div>
      <%= simple_form_for([@cocktail, @dose]) do |f| %>
      <div class='form-input'>
        <%= f.input :description %>
        <%= f.association :ingredient %>
        <div class="btn mt-2 pl-0 mb-4">
          <%= f.button :submit, 'Update', class:'dose-btn', method: :patch, data: { confirm: "Are you sure?" } %>
        </div>
        <% end %>


      </div>
    </div>
  </div>
</div>

rails-mister-cocktail/app/views/doses/index.html.erb
<h1>Doses#index</h1>
<p>Find me in app/views/doses/index.html.erb</p>

rails-mister-cocktail/app/views/doses/new.html.erb
<div class="banner">
  <div class="container d-flex justify-content-start">
    <div class="cocktail-show">
      <h1><%= @cocktail.name %></h1>
      <div class="cocktail-recipe">
        <% counter = 0 %>
        <% @cocktail.doses.each do |dose| %>
        <div class="d-flex align-items-center justify-content-between">
          <p class="mb-4" style="font-size: 1.1em"><span class="counter"><%= counter += 1 %></span><%= dose.description.capitalize %> of <%= dose.ingredient.name.capitalize %>
        </p>
        <div class="btn pl-0 mb-4">
          <%= link_to dose_path(dose), class:'link-icon last', method: :delete, data: { confirm: "Are you sure?" } do %>
          <i class="fas fa-trash-alt"></i>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
    <%= simple_form_for([@cocktail, @dose]) do |f| %>
    <div class='form-input'>
      <%= f.input :description %>
      <%= f.association :ingredient %>
      <div class="btn mt-2 pl-0 mb-4">
        <% if @cocktail.doses.count < 1 %>
        <%= f.button :submit, 'Add to recipe', class:'dose-btn' %>
        <% else %>
        <%= f.button :submit, 'Add to recipe', class:'dose-btn' %>
        <%= link_to "No more ingredient needed", cocktail_path(@cocktail) %>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>

rails-mister-cocktail/app/views/doses/show.html.erb
<h1>Doses#show</h1>
<p>Find me in app/views/doses/show.html.erb</p>

rails-mister-cocktail/app/views/ingredients/new.html.erb
blabla

rails-mister-cocktail/app/views/layouts/application.html.erb
<!DOCTYPE html>


<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


  </head>

  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon ">
  <%= link_to root_path, class: "navbar-brand" do %>
    <h1 class="nav-title">Mister Cocktails</h1>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

</div>

  </div>

    <%= yield %>

    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
</body>
  </body>
</html>

rails-mister-cocktail/app/views/pages/home.html.erb
<div class="banner-home d-flex  align-items-center">
  <div class="container d-flex justify-content-center align-items-center">
    <div class="home">
      <h1 class=" d-flex align-items-center ">Mister Cocktails</h1>

      <div class="d-flex justify-content-center">
      <%= link_to "Join now", cocktails_path %>
    </div>
    </div>
  </div>
</div>

rails-mister-cocktail/app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

rails-mister-cocktail/app/views/reviews/new.html.erb
<div class="banner d-flex align-items-center">
  <div class="container d-flex justify-content-start align-items-center">
    <div class="cocktail-show mt-4">
      <h2 style="font-size: 3.5em">Review</h2>
      <h1><%= @cocktail.name %></h1>
      <div class="cocktail-recipe">
        <%= simple_form_for([@cocktail, @review]) do |f| %>
        <div class='form-input'>
          <%= f.input :rating, collection: 0..5 %>
          <%= f.input :content %>
          <div class="btn mt-2 pl-0 mb-4">
            <%= f.button :submit, 'Add your review', class:'dose-btn' %>
            <%= link_to "Back to Cocktails", cocktails_path %>

          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>